    <!-- FOOTER -->
    <footer id="contact" class="text-white">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-5">
                    <h2>Nous contacter</h2>
                    <div>
                        <img src="assets/img/contact.png" alt="contact">
                    </div>

                    <address class="mt-3 text-center">
                        35 rue Marenro<br>
                        13006 Marseille
                    </address>

                    <div class="footer-icons text-center mt-5">
                        <!-- la class text-decoration-none évite d'avoir des traits entre les images cliquables -->
                        <a class="text-decoration-none" href="#">
                            <img class="mx-2" src="assets/img/logo-facebook.png" alt="Facebook">
                        </a>
                        <a class="text-decoration-none" href="#">
                            <img class="mx-2" src="assets/img/logo-instagram.png" alt="Instagram">
                        </a>
                        <a class="text-decoration-none" href="#">
                            <img class="mx-2" src="assets/img/logo-messenger.png" alt="Messenger">
                        </a>
                    </div>
                </div>

                <div class="col-12 col-lg-7 mt-5 mt-lg-0">
                    <form action="#" method="post">
                        <div>
                            <input class=" border-0 mb-3 py-3 px-3 rounded-pill" type="text" name="last_nane" id=""
                                placeholder="Nom" value="">
                        </div>
    
                        <div>
                            <input class=" border-0 mb-3 py-3 px-3 rounded-pill" type="email" name="email" id=""
                                placeholder="Email" value="">
                        </div>
    
                        <div>
                            <textarea class=" border-0 mb-3 py-3 px-3 " name="message" id=""
                                placeholder="Message"></textarea>
                        </div>
    
                        <div class="text-center">
                            <button class="border-0 px-4 py-2 rounded-pill shadow-sm text-white"
                                type="submit">Envoyer</button>
                        </div>
                    </form>
                </div>
            </div>

            <p class="mt-5 mb-0 py-4 text-center">
                &copy; La passerelle - 2024 - Lhassan Alhmoum
            </p>
        </div>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>

</html>