<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $title ?></title>

    <!-- Boostrap 5 library -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400&display=swap"
        rel="stylesheet">

        <!-- Deux fichiers CSS d'aide à la visualisation (facultatifs). Utilisable individuellement ou ensembles -->
    <!-- <link rel="stylesheet" href="assets/css/zoning.css"> -->
    <!-- <link rel="stylesheet" href="assets/css/bootstrap-grid-system.css"> -->

    <!-- Style CSS CornFood -->
    <link rel="stylesheet" href="assets/css/style.css">
</head>