<!DOCTYPE html>
<html lang="fr">

<?php include './templates/blocs/head.phtml' ?>

<!-- Quand vous avez plusieurs pages dans votre site, pensez à donner un id (ou une classe unique) pour être en mesure de différencier les page dans votre css qui sera commun -->
<body id="page-index"> 
    <!-- HEADER -->
    <header class="pt-3 px-3">
        <div class="container">

            <?php include './templates/blocs/nav.phtml' ?>

            <div class="titre text-center text-white">
                <h1 class="mb-4 text-uppercase">Des encas sains pour la journée</h1>

                <p>Des produits sains à base de blé bio à grignoter pendant la journée </p>
                <a class="btn btn-light btn-lg rounded-pill text-warning" href="#decouvrir">Découvrir</a>
            </div>

            <!-- Pensez au triangle -->
            <div class="content-triangle text-center">
                <div class="triangle"></div> <!-- voir le css -->
            </div>
        </div>
    </header>

    <!-- MAIN -->
    <main>
        <!-- Fil d'arianne -->
        <div id="breadcrumb">
            <div class="container">
                <nav class="mt-3" aria-label="breadcrumb">
                    <menu class="breadcrumb px-3 px-sm-0">
                        <li class="breadcrumb-item active">
                            Cornfood
                        </li>
                    </menu>
                </nav>
            </div>
        </div>

        <section id="concept" class="concept mt-5 px-3">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-sm-6 col-lg-4">
                        <!-- J'ai opté pour ajouter une div qui recevra l'image-de fond. C'est finalement plus simple à faire avec une div en plus -->
                        <div class="titre mb-4 mb-lg-0">
                            <h2 class="text-end">
                                Du naturel<br>
                                au goûter&nbsp;?
                            </h2>
                        </div>
                    </div>

                    <!-- J'ai opté d'appler les image-qui illustrent les article en image-de fond. Plus simple à gérer que le flexbox (cf. CSS) -->
                    <div class="col-12 col-lg-4">
                        <article class="naturel d-flex">
                            <div class="me-3">
                                <img src="assets/img/organic-2.png" alt="Icône feuille d'arbre stylisée">
                            </div>
                            <div>
                                <h3>
                                    Du naturel
                                </h3>
                                <!-- La class fs-7 a été crée par moi et correspond à un font-size de 0.85rem (cf. CSS) -->
                                <p class="fs-7">
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa delectus facilis quisquam dolor ducimus suscipit, quae a est dicta magni expedita velit corporis deleniti, maxime dolore tempora dolores.
                                </p>
                            </div>
                        </article>
                    </div>

                    <div class="col-12 col-lg-4">
                        <article class="bio d-flex">
                            <div class="me-3">
                                <img src="assets/img/organic-1.png" alt="Icône d'arbre stylisée">
                            </div>
                            <div>
                                <h3>
                                    Exploitation bio
                                </h3>
                                <p class="fs-7">
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa delectus facilis quisquam dolor ducimus suscipit, quae a est dicta magni expedita velit corporis deleniti, maxime dolore tempora dolores.
                                </p>
                            </div>
                        </article>
                    </div>
                </div>

                <div class="row mt-4">
                    <div class="col-12 offset-lg-4 col-lg-4">
                        <article class="encas d-flex">
                            <div class="me-3">
                                <img src="assets/img/detox.png" alt="icône verre avec paille stylisé">
                            </div>
                            <div>
                                <h3>
                                    Un encas sain
                                </h3>
                                <p class="fs-7">
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa delectus facilis quisquam dolor ducimus suscipit, quae a est dicta magni expedita velit corporis deleniti, maxime dolore tempora dolores.
                                </p>
                            </div>
                        </article>
                    </div>

                    <div class="col-12 col-lg-4">
                        <article class="calorie d-flex">
                            <div class="me-3">
                                <img src="assets/img/grain-1.png" alt="Grains de céréales stylisés">
                            </div>
                            <div>
                                <h3>
                                    Faible en calorie
                                </h3>
                                <p class="fs-7">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa delectus facilis quisquam dolor ducimus suscipit, quae a est dicta magni expedita velit corporis deleniti, maxime dolore tempora dolores.</p>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
        </section>

        <section id="decouvrir" class="decouvrir text-center px-3 my-5">
            <div class="container shadow-decouvrir">
                <h2 class="my-5 text-pink">Produits à découvrir</h2>
                <div class="row mb-5">
                    <div class="col-12 col-lg-6 border-dashed-end">
                        <div class="row">
                            <div class="col-12">
                                <h3 class="text-center my-5 mt-sm-0">
                                    Nos produits chocolatés
                                </h3>
                            </div>
                            
                            <div class="col-12 col-sm-6 col-lg-6">
                                <article>
                                    <img src="assets/img/image-1.png" alt="Barre protéinée">
                                    <h3 class="my-4">Barre protéinée</h3>
                                    <p>1,50€</p>
                                </article>
                            </div>
        
                            <div class="col-12 col-sm-6 col-lg-6">
                                <article>
                                    <img src="assets/img/image-2.png" alt="Pâte à tartiner">
                                    <h3 class="my-4">Pâte à tartiner</h3>
                                    <p>5,49€</p>
                                </article>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-lg-6 mt-5 mt-lg-0">
                        <div class="row">
                            <div class="col-12">
                                <h3 class="text-center my-5 mt-sm-0">
                                    Nos produits détox
                                </h3>
                            </div>
                            <div class="col-12 col-sm-6 col-lg-6">
                                <article>
                                    <img src="assets/img/image-3.png" alt="Thé détox">
                                    <h3 class="my-4">Thé détox</h3>
                                    <p>14,50€</p>
                                </article>
                            </div>
        
                            <div class="col-12 col-sm-6 col-lg-6">
                                <article>
                                    <img src="assets/img/image-4.png" alt="Charbon acrif">
                                    <h3 class="my-4">Charbon acrif</h3>
                                    <p>8,10€</p>
                                </article>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

    <?php include './templates/blocs/footer.phtml' ?>
    <?php include './templates/blocs/script.phtml' ?>

</body>

</html>