<!DOCTYPE html>
<html lang="fr">

<?php include './templates/blocs/head.phtml' ?>


<body id="page-produits">
    <!-- HEADER -->
    <header>
        <div class="container">

            <?php include './templates/blocs/nav.phtml' ?>

            <div class="titre text-center text-white">
                <h1 class="mb-4 text-uppercase">Nos produits</h1>
                <p>Des produits sains à base de blé bio à grignoter pendant la journée </p>
            </div>

            <!-- triangle -->
            <div class="content-triangle text-center">
                <div class="triangle"></div> <!-- voir le css -->
            </div>
        </div>
    </header>

    <!-- MAIN -->
    <main>
        <!-- Fil d'arianne -->
        <div id="breadcrumb">
            <div class="container">
                <nav class="mt-3" aria-label="breadcrumb">
                    <menu class="breadcrumb px-3 px-sm-0">
                        <li class="breadcrumb-item">
                            <a class="text-black text-decoration-none" href="index.php">Cornfood</a>
                        </li>

                        <li class="breadcrumb-item active">
                            Produits
                        </li>
                    </menu>
                </nav>
            </div>
        </div>

        <!-- section des produits phares avec carousel -->
        <section id="produits-phares" class="mt-5">
            <div class="container">
                <!-- La class text-pink est une création, pas une class de bootstrap -->
                <h2 class="text-pink mb-4">Nos produits phares</h2>

                <!-- NOTE : j'ai recadré les images pour qu'elles fassent toutes les 3 les mêmes dimensions : 1150px x 420px -->
                <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-indicators d-none">
                        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0"
                            class="active" aria-current="true" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                            aria-label="Slide 2"></button>
                        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                            aria-label="Slide 3"></button>
                    </div>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="assets/img/carousel/granola.jpg" class="d-block w-100" alt="Granola">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Granola</h5>
                                <p>Un granola d'exeption, gourmand et allégé en sucre</p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img src="assets/img/carousel/juice.jpg" class="d-block w-100" alt="Juices">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Second slide label</h5>
                                <p>Some representative placeholder content for the second slide.</p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img src="assets/img/carousel/latte.jpg" class="d-block w-100" alt="Latte">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Third slide label</h5>
                                <p>Some representative placeholder content for the third slide.</p>
                            </div>
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
                        data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
                        data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </section>

        <!-- section des produit à découvrir -->
        <section id="produits-decouvrir" class="produits text-center px-3">
            <div class="container">
                <h2 class="my-5 text-pink">Produits à découvrir</h2>

                <div class="row mb-5">
                    <?php foreach($products as $id => $product) : ?>
                        <div class="col-12 col-lg-4">
                            <article>
                                <!-- L'adresse URL ici présente se termine par un point d'interrogation suivit du nom du produit. C'est ce que l'on appel un paramètre URL et permet au développeur backend d'afficher le bon produit grâce à une condition -->
                                <a href="produit.php?id=<?=$id?>">
                                    <img src="assets/img/products/<?=$product['image']?>" alt="<?=$product['name']?>" style="width: auto; height: 200px">
                                </a>
        
                                <h3 class="my-4">
                                    <a class="text-black text-decoration-none" href="produit.php?id=<?=$id?>"><?=$product['name']?></a>
                                </h3>
        
                                <p>
                                    <a class="text-black text-decoration-none" href="produit.php?id=<?=$id?>"><?=number_format($product['price'], 2, ',', ' ')?>€</a>
                                </p>
                            </article>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </section>

        
    </main>

    <?php include './templates/blocs/footer.phtml' ?>
    <?php include './templates/blocs/script.phtml' ?>

</body>

</html>